name: AutoWhitelistRemoveDSRV
version: ${project.version}
main: lol.shadowdev.autowhitelistremovedsrv.AutoWhitelistRemoveDSRV
api-version: 1.13
author: thewilloftheshadow
website: "https://github.com/thewilloftheshadow/AutoWhitelistRemove-DSRV"
description: Automatically remove inactive players from your subscriber role in DiscordSRV
permissions:
    autowhitelistremovedsrv.check:
        default: op
        description: Allows the usage of /awrd check
    autowhitelistremovedsrv.reload:
        default: op
        description: Allows the usage of /awrd reload
commands:
    awrd:
        usage: /awrd
        permission: autowhitelistdsrv.check
