name: AutoWhitelistRemove
version: ${project.version}
main: lol.shadowdev.autowhitelistremovedsrv.AutoWhitelistRemove
api-version: 1.13
api: "1.13"
author: thewilloftheshadow
website: https://www.spigotmc.org/resources/autowhitelistremove.93326/
description: Automatically remove inactive players from your subscriber role in DiscordSRV
permissions:
  autowhitelistremovedsrv.check:
    default: op
    description: Allows the usage of /awrd check
  autowhitelistremovedsrv.reload:
    default: op
    description: Allows the usage of /awrd reload
commands:
  awr:
    usage: /awrd
    permission: autowhitelistdsrv.check